(function(){'use strict';
var core=window.MushijingiToolboxCore,catalog=window.MushijingiRegistryCatalog,runtime=window.MushijingiDeckRuntime;
var cards=[],byId=Object.create(null),store,el={},selected=null;
var labels={INSECT:'虫',SPELL:'術',ENHANCEMENT:'強化',RED:'赤',BLUE:'青',GREEN:'緑',COLORLESS:'無色',TESTED:'対戦対応',IMPLEMENTED:'対戦対応',SPEC_COMPLETE:'対戦対応',PARTIAL:'一部対応',BLOCKED:'確認保留',NOT_RESEARCHED:'未実装',RESEARCHED:'調査済み'};
function esc(v){return String(v==null?'-':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function label(v){return labels[v]||String(v==null?'-':v);}
function id(){return'deck:toolbox:'+Date.now().toString(36)+Math.floor(Math.random()*1679616).toString(36).padStart(4,'0');}
function makeDeck(){return core.createDeck({deckId:id(),deckName:core.DEFAULT_DECK_NAME,cardDataVersion:'card-registry/1',rulesetId:'ruleset:standard:v1'});}
function active(){return store.decks.find(function(d){return d.deckId===store.activeDeckId;})||null;}
function ensure(){var d=active();if(d)return d;d=makeDeck();store.decks.push(d);store.activeDeckId=d.deckId;return d;}
function replace(d){store.decks=store.decks.map(function(x){return x.deckId===d.deckId?d:x;});}
function currentFilters(){return{query:el.search.value,set:el.set.value,type:el.type.value,color:el.color.value,cost:el.cost.value,rarity:el.rarity.value,implementationStatus:el.status.value};}
function cardRow(c){return'<article class="card-row color-'+esc(String(c.color||'unknown').toLowerCase())+'"><button class="card-open" data-card-id="'+esc(c.cardId)+'"><span class="card-number">'+esc(c.officialNumber)+'</span><span class="card-name">'+esc(c.name)+'</span><span class="card-id">'+esc(c.set)+'</span><span class="card-facts"><span>'+esc(label(c.type))+'</span><span>'+esc(label(c.color))+'</span><span>Cost '+esc(c.cost)+'</span><span>HP '+esc(c.baseHp)+'</span><span>'+esc(c.rarity)+'</span><span>'+esc(label(c.implementationStatus))+'</span></span></button><button class="card-add" data-add="'+esc(c.cardId)+'">＋ デッキ</button></article>';}
function renderCards(){var found=core.sortCatalog(core.filterCatalog(cards,currentFilters()),el.sort.value);el.count.textContent=found.length+'件 / '+cards.length+'件';el.empty.hidden=!!found.length;el.list.innerHTML=found.map(cardRow).join('');el.list.querySelectorAll('[data-card-id]').forEach(function(b){b.onclick=function(){detail(b.dataset.cardId);};});el.list.querySelectorAll('[data-add]').forEach(function(b){b.onclick=function(){add(b.dataset.add);};});}
function effects(a){return!a||!a.length?'-':'<ul>'+a.map(function(x){return'<li>'+esc(x.name||x.effectText||x.text||JSON.stringify(x))+'</li>';}).join('')+'</ul>';}
function detail(cardId){var c=byId[cardId];if(!c)return;selected=cardId;el.detailContent.innerHTML='<header class="detail-title-block"><p>'+esc(c.officialNumber)+' / '+esc(c.set)+'</p><h2 id="detail-title">'+esc(c.name)+'</h2></header><div class="detail-basics"><div><span>種類</span>'+esc(label(c.type))+'</div><div><span>色</span>'+esc(label(c.color))+'</div><div><span>コスト</span>'+esc(c.cost)+'</div><div><span>HP</span>'+esc(c.baseHp)+'</div><div><span>レアリティ</span>'+esc(c.rarity)+'</div><div><span>対戦対応</span>'+esc(label(c.implementationStatus))+'</div></div><section class="detail-section"><h3>技・特性</h3>'+effects((c.skills||[]).concat(c.passiveAbilities||[]))+'</section><section class="detail-section"><h3>効果</h3>'+effects((c.cardEffects||[]).concat(c.enhancementEffects||[]))+'</section>';el.detail.showModal();}
function total(deck){return(deck.cards||[]).reduce(function(n,x){return n+x.quantity;},0);}
function add(cardId){var c=byId[cardId],d=ensure(),same=0;if(!c)return;d.cards.forEach(function(x){var other=byId[x.canonicalCardId];if(other&&other.name===c.name)same+=x.quantity;});if(total(d)>=20){el.message.textContent='20枚に達しています。';return;}if(same>=2){el.message.textContent='同名カードは合計2枚までです。';return;}replace(core.addCatalogCard(d,c));el.message.textContent=c.name+'を追加しました（保存前）';renderDeck();}
function deckEntry(x){var c=byId[x.canonicalCardId];return'<article class="deck-entry"><div class="deck-entry-info"><strong>'+esc(c?c.name:x.canonicalCardId)+'</strong><small>'+esc(c?label(c.implementationStatus):'不明なカード')+'</small></div><div class="quantity-controls"><button data-dec="'+esc(x.printingId)+'">−</button><b>'+x.quantity+'</b><button data-inc="'+esc(x.canonicalCardId)+'">＋</button></div><button class="remove-card" data-remove="'+esc(x.printingId)+'">削除</button></article>';}
function renderDeck(){var d=ensure(),v=core.validateDeck(d,cards);el.selector.innerHTML=store.decks.map(function(x){return'<option value="'+esc(x.deckId)+'">'+esc(x.deckName)+'</option>';}).join('');el.selector.value=d.deckId;el.name.value=d.deckName;el.deckTotal.textContent=v.totalCards+' / 20';el.navTotal.textContent=v.totalCards;el.entryCount.textContent=d.cards.length+'種類';el.emptyDeck.hidden=!!d.cards.length;el.deckList.innerHTML=d.cards.map(deckEntry).join('');el.deckStats.innerHTML='<div><strong>'+v.totalCards+'</strong><span>合計</span></div>';el.costStats.textContent=v.battleReady?'対戦可能な20枚デッキです。':v.errors.concat(v.warnings).join(' ');el.battle.disabled=!v.battleReady;el.deckList.querySelectorAll('[data-inc]').forEach(function(b){b.onclick=function(){add(b.dataset.inc);};});el.deckList.querySelectorAll('[data-dec]').forEach(function(b){b.onclick=function(){replace(core.decrementCard(active(),b.dataset.dec));renderDeck();};});el.deckList.querySelectorAll('[data-remove]').forEach(function(b){b.onclick=function(){replace(core.removeCard(active(),b.dataset.remove));renderDeck();};});}
function persist(msg){try{localStorage.setItem(core.DECK_STORAGE_KEY,core.serializeDeckStore(store));el.message.textContent=msg;}catch(e){el.message.textContent='保存できませんでした。';}}
function save(){var d=core.buildDeckFormat(core.renameDeck(ensure(),el.name.value));replace(d);persist('「'+d.deckName+'」を保存しました。');renderDeck();}
function view(name){el.cardsView.hidden=name!=='cards';el.decksView.hidden=name!=='decks';document.querySelectorAll('[data-view]').forEach(function(b){b.classList.toggle('active',b.dataset.view===name);});if(name==='decks')renderDeck();}
function options(){var values=core.deriveFilterOptions(cards);['set','type','color','cost','rarity','implementationStatus'].forEach(function(k){var select=el[k==='implementationStatus'?'status':k];values[k].forEach(function(v){var o=document.createElement('option');o.value=v;o.textContent=label(v);select.appendChild(o);});});}
function bind(){[el.search,el.set,el.type,el.color,el.cost,el.rarity,el.status,el.sort].forEach(function(x){x.addEventListener(x===el.search?'input':'change',renderCards);});el.clear.onclick=function(){[el.search,el.set,el.type,el.color,el.cost,el.rarity,el.status].forEach(function(x){x.value='';});renderCards();};el.close.onclick=function(){el.detail.close();};el.detailAdd.onclick=function(){add(selected);};el.save.onclick=save;el.duplicate.onclick=function(){var d=core.duplicateDeck(ensure(),{deckId:id()});store.decks.push(d);store.activeDeckId=d.deckId;persist('デッキを複製しました。');renderDeck();};el.newDeck.onclick=function(){var d=makeDeck();store.decks.push(d);store.activeDeckId=d.deckId;renderDeck();};el.deleteDeck.onclick=function(){var d=active();if(!d||!confirm('「'+d.deckName+'」を削除しますか？'))return;store.decks=store.decks.filter(function(x){return x.deckId!==d.deckId;});store.activeDeckId=store.decks[0]?store.decks[0].deckId:null;ensure();persist('デッキを削除しました。');renderDeck();};el.battle.onclick=function(){save();sessionStorage.setItem(runtime.HANDOFF_KEY,active().deckId);location.href='index.html?deck='+encodeURIComponent(active().deckId);};el.selector.onchange=function(){store.activeDeckId=el.selector.value;renderDeck();};el.name.oninput=function(){replace(core.renameDeck(active(),el.name.value));};document.querySelectorAll('[data-view]').forEach(function(b){b.onclick=function(){view(b.dataset.view);};});}
function init(){var m={search:'search-input',set:'set-filter',type:'type-filter',color:'color-filter',cost:'cost-filter',rarity:'rarity-filter',status:'status-filter',sort:'sort-select',clear:'clear-filters',count:'result-count',list:'card-list',empty:'empty-message',detail:'card-detail',close:'close-detail',detailAdd:'detail-add',detailContent:'detail-content',cardsView:'cards-view',decksView:'decks-view',selector:'deck-selector',name:'deck-name',save:'save-deck',duplicate:'duplicate-deck',newDeck:'new-deck',deleteDeck:'delete-deck',battle:'battle-deck',message:'storage-message',deckTotal:'deck-total',navTotal:'nav-deck-total',deckStats:'deck-stats',costStats:'cost-stats',entryCount:'deck-entry-count',emptyDeck:'empty-deck-message',deckList:'deck-list'};Object.keys(m).forEach(function(k){el[k]=document.getElementById(m[k]);});cards=catalog.fromRegistry(window.cardRegistry);cards.forEach(function(c){byId[c.cardId]=c;});store=core.parseDeckStore(localStorage.getItem(core.DECK_STORAGE_KEY));ensure();options();bind();el.list.setAttribute('aria-busy','false');renderCards();renderDeck();var edit=new URLSearchParams(location.search).get('edit');if(edit&&store.decks.some(function(d){return d.deckId===edit;})){store.activeDeckId=edit;view('decks');}if(store.recoveryWarning)el.message.textContent=store.recoveryWarning;}
document.addEventListener('DOMContentLoaded',init);
}());
