'use strict';
var TestRunner=require('./lib.js');require('./engine-loader.js');require('../js/engine/cpu-agent.js');var h=require('./helpers.js');var runner=new TestRunner();
function main(s){if(s.phase===Phases.DRAW_PHASE)enterSetPhase(s);if(s.phase===Phases.SET_PHASE)enterMainPhase(s);}
function nextManual(){var s=h.newGame({rng:h.firstPlayerRng});main(s);s.manualDrawPlayers=['P2'];endTurn(s);return s;}
function ev(s,t){return getBattleEventsSince(s,0).filter(function(e){return e.type===t;});}
function battle(a,d){var s=h.newGame({rng:h.firstPlayerRng});main(s);return{s:s,a:h.putInsectOnField(s,'P1',a),d:h.putInsectOnField(s,'P2',d,{hp:5000})};}
runner.test('FoundationDraw1 通常ドロー後SETへ自動遷移',function(){var s=nextManual();runner.assertEqual(s.phase,Phases.DRAW_PHASE);runner.assertEqual(s.player('P2').hand.length,4);drawCardOnce(s,'P2');runner.assertEqual(s.player('P2').hand.length,5);runner.assertEqual(s.phase,Phases.SET_PHASE);});
runner.test('FoundationDraw2 先攻初手は無ドローでSET',function(){var s=h.newGame({rng:h.firstPlayerRng});runner.assertEqual(s.player('P1').hand.length,4);runner.assertEqual(s.drewThisTurn,false);runner.assertEqual(s.phase,Phases.SET_PHASE);});
runner.test('FoundationDraw3 SET自動遷移は1回',function(){var s=nextManual();drawCardOnce(s,'P2');var threw=false;try{drawCardOnce(s,'P2');}catch(e){threw=true;}runner.assertTrue(threw);runner.assertEqual(s.battleLog.filter(function(x){return x.text==='P2 はセットフェイズへ';}).length,1);});
runner.test('FoundationEvent1 Human DAMAGEは1回',function(){var b=battle('test_red_1','test_blue_1');performAttack(b.s,b.a.instanceId,b.d.instanceId,'INSECT','attack');runner.assertEqual(ev(b.s,'DAMAGE').length,1);});
runner.test('FoundationEvent2 CPU DAMAGEも発生',function(){var b=battle('test_red_1','test_blue_1');b.s.player('P1').field=[b.d];b.s.player('P2').field=[b.a];b.a.ownerId=b.a.controllerId='P2';b.d.ownerId=b.d.controllerId='P1';b.s.activePlayerId='P2';var cpu=new CpuAgent('P2',{rng:function(){return 0;}});runner.assertTrue(cpu.executeAction(b.s,{type:'ATTACK',attackerInstanceId:b.a.instanceId,targetInstanceId:b.d.instanceId,targetType:'INSECT',skillId:'attack'}));runner.assertEqual(ev(b.s,'DAMAGE').length,1);});
runner.test('FoundationEvent3 DAMAGE payloadが正しい',function(){var b=battle('test_red_1','test_blue_1');performAttack(b.s,b.a.instanceId,b.d.instanceId,'INSECT','attack');var e=ev(b.s,'DAMAGE')[0];runner.assertEqual(e.sourceInstanceId,b.a.instanceId);runner.assertEqual(e.targetInstanceId,b.d.instanceId);runner.assertEqual(e.damage,500);runner.assertEqual(e.damageType,'ATTACK');runner.assertEqual(e.skillId,'attack');});
runner.test('FoundationEvent4 色倍率を保持',function(){var b=battle('test_red_1','test_green_1');performAttack(b.s,b.a.instanceId,b.d.instanceId,'INSECT','attack');var e=ev(b.s,'DAMAGE')[0];runner.assertEqual(e.baseDamage,500);runner.assertEqual(e.colorMultiplier,2);runner.assertEqual(e.damage,1000);});
function el(){return{style:{},textContent:'',getBoundingClientRect:function(){return{left:20,top:30,width:60,height:80};}};}
function uiFixture(fn){var es={'damage-vector':el(),'damage-vector-line':el(),'damage-vector-label':el()},oldDocument=global.document,oldWindow=global.window;global.window=global;global.innerWidth=390;global.innerHeight=844;global.document={getElementById:function(id){return es[id]||null;},querySelector:function(){return el();}};require('../js/ui/battle-ui.js');try{fn(es);}finally{global.document=oldDocument;global.window=oldWindow;}}
runner.test('FoundationUI1 DAMAGE vectorを表示',function(){uiFixture(function(es){var u=Object.create(BattleUI.prototype);u.state={battleEvents:[{id:1,type:'DAMAGE',sourceInstanceId:'a',targetInstanceId:'d',sourceName:'オオカマキリ',targetName:'カブトムシ',baseDamage:500,damage:1000,damageType:'ATTACK',colorMultiplier:2}]};u.actionState={mode:'idle'};u._lastBattleEventId=0;u._damageVectorQueue=[];u.renderBattleEvents();runner.assertEqual(es['damage-vector'].style.display,'block');runner.assertTrue(es['damage-vector-label'].textContent.indexOf('500 ×2 = 1000')!==-1);});});
runner.test('FoundationUI2 表示終了後も通常操作',function(){uiFixture(function(es){var old=setTimeout,cb;global.setTimeout=function(f){cb=f;return 1;};try{var u=Object.create(BattleUI.prototype);u.state={battleEvents:[{id:1,type:'DAMAGE',sourceInstanceId:'a',targetInstanceId:'d',baseDamage:500,damage:500,damageType:'ATTACK',colorMultiplier:1}]};u.actionState={mode:'idle'};u._lastBattleEventId=0;u._damageVectorQueue=[];u.renderBattleEvents();cb();runner.assertEqual(es['damage-vector'].style.display,'none');runner.assertEqual(u.actionState.mode,'idle');}finally{global.setTimeout=old;}});});
if(require.main===module)runner.runAll();module.exports=runner;
