'use strict';
require('./engine-loader.js');require('../js/engine/cpu-agent.js');
var h=require('./helpers.js'),Runner=require('./lib.js'),runner=new Runner();
function fixture(){var s=h.newGame({rng:h.firstPlayerRng});h.toMainPhase(s);s.turnNumber=3;s.player('P1').hand=[];s.player('P2').field=[];s.player('P2').territory=[];return s;}
function definition(id,skills){var raw=JSON.parse(JSON.stringify(global.getCardDefinition('set1_003')));raw.id=id;raw.set=null;raw.implementationStatus='test';raw.skills=skills;var d=new global.CardDefinition(raw);global.cardRegistry.register(d);return d;}
runner.test('CPU skips consumed once-per-field skill and uses legal fallback',function(){var d=definition('cpu_once_legal',[{id:'once',timing:'ATTACK',baseAp:100,usageLimit:'ONCE_PER_FIELD_STAY'},{id:'normal',timing:'ATTACK',baseAp:100}]),s=fixture(),a=h.putInsectOnField(s,'P1',d.id);a.usedSkills=['once'];var cpu=new global.CpuAgent('P1',{rng:function(){return 0;}}),action=cpu.decideMainPhaseAction(s);runner.assertEqual(action.skillId,'normal');runner.assert(cpu.executeAction(s,action));});
runner.test('CPU ends turn when only insect-only skill lacks an insect target',function(){var d=definition('cpu_insect_only',[{id:'insect',timing:'ATTACK',baseAp:100,targetRule:'INSECT_ONLY'}]),s=fixture();h.putInsectOnField(s,'P1',d.id);var cpu=new global.CpuAgent('P1');runner.assertEqual(cpu.decideMainPhaseAction(s).type,'END_TURN');});
runner.test('CPU skips two-target skill with one target and uses fallback',function(){var d=definition('cpu_multi_legal',[{id:'multi',timing:'ATTACK',baseAp:100,effects:[{type:'ATTACK_MULTIPLE_TARGETS',exactSelections:2}]},{id:'normal',timing:'ATTACK',baseAp:100}]),s=fixture();h.putInsectOnField(s,'P1',d.id);h.putInsectOnField(s,'P2','set1_003');var cpu=new global.CpuAgent('P1',{rng:function(){return 0;}}),action=cpu.decideMainPhaseAction(s);runner.assertEqual(action.skillId,'normal');runner.assert(cpu.executeAction(s,action));});
module.exports=runner;if(require.main===module)runner.runAll();
