'use strict';
var TestRunner=require('./lib.js');require('./engine-loader.js');require('../js/engine/cpu-agent.js');require('../js/engine/cpu-runner.js');var h=require('./helpers.js');var runner=new TestRunner();
function setup(count){var s=h.newGame({rng:h.firstPlayerRng});s.activePlayerId='P2';s.turnNumber=2;s.phase=Phases.MAIN_PHASE;s.pendingEffect=null;s.player('P2').hand=[];s.player('P2').field=[];s.player('P2').availableCost=1;var discarded=[];for(var i=0;i<count;i++){var c=h.addToHandRaw(s,'P2',h.defById(i%2?'test_blue_1':'test_red_1'));moveCard(s,c.instanceId,ZONES.HAND,ZONES.DISCARD,{playerId:'P2'});discarded.push(c);}var spell=h.addToHandRaw(s,'P2',h.defById('niji_no_kakehashi'));return{s:s,discarded:discarded,spell:spell};}
function runCpu(f,rng,max){var ui={render:function(){}};var cr=new CpuRunner({state:f.s},ui,{rng:rng||function(){return .99;},thinkDelay:1,maxActionsPerTurn:max||20});return cr.runTurn().then(function(){return cr;});}
runner.test('CpuRainbow1 候補1枚を自動回収してターン継続',function(){var f=setup(1);return runCpu(f).then(function(cr){runner.assertEqual(f.s.pendingEffect,null);runner.assertTrue(f.s.player('P2').hand.some(function(c){return c.instanceId===f.discarded[0].instanceId;}));runner.assertEqual(f.spell.zone,ZONES.DISCARD);runner.assertEqual(f.s.activePlayerId,'P1');runner.assertEqual(cr.isRunning,false);});});
runner.test('CpuRainbow2 複数候補pendingをCPU自身が解決',function(){var f=setup(2);return runCpu(f).then(function(cr){runner.assertEqual(f.s.pendingEffect,null);runner.assertTrue(f.s.player('P2').hand.some(function(c){return c.instanceId===f.discarded[1].instanceId;}));runner.assertTrue(f.s.player('P2').discard.some(function(c){return c.instanceId===f.discarded[0].instanceId;}));runner.assertEqual(f.s.activePlayerId,'P1');runner.assertTrue(cr.actionsThisTurn<20);});});
runner.test('CpuRainbow3 解決後の次CPUターンもfreezeしない',function(){var f=setup(2);return runCpu(f).then(function(cr){if(f.s.phase===Phases.SET_PHASE)enterMainPhase(f.s);endTurn(f.s);runner.assertEqual(f.s.activePlayerId,'P2');if(f.s.phase===Phases.SET_PHASE)enterMainPhase(f.s);f.s.player('P2').hand=[];f.s.player('P2').field=[];return cr.runTurn();}).then(function(){runner.assertEqual(f.s.pendingEffect,null);runner.assertEqual(f.s.activePlayerId,'P1');});});
runner.test('CpuRainbow4 P1所有pendingは解決せず安全停止',function(){var f=setup(2);f.s.pendingEffect={type:'DISCARD_INSECT_SELECTION',playerId:'P1',options:['human-choice']};return runCpu(f).then(function(cr){runner.assertEqual(f.s.pendingEffect.playerId,'P1');runner.assertEqual(cr.actionsThisTurn,0);runner.assertEqual(cr.isRunning,false);});});
runner.test('CpuRainbow5 GAME_OVER後はCPU処理を再開しない',function(){var f=setup(2);f.s.phase=Phases.GAME_OVER;f.s.winner='P1';return runCpu(f).then(function(cr){runner.assertEqual(cr.actionsThisTurn,0);runner.assertEqual(f.s.pendingEffect,null);runner.assertEqual(cr.isRunning,false);});});
if(require.main===module)runner.runAll();module.exports=runner;
