'use strict';
require('./engine-loader.js');
var h=require('./helpers.js'),Runner=require('./lib.js'),runner=new Runner();
function fixture(){var s=h.newGame({rng:h.firstPlayerRng});h.toMainPhase(s);s.turnNumber=3;s.player('P1').territory=[];s.player('P2').territory=[];return s;}
runner.test('Temporary self HP raises the attacker only during next opponent turn',function(){var s=fixture(),a=h.putInsectOnField(s,'P1','set1_070'),t=h.putInsectOnField(s,'P2','set1_003',{hp:5000});global.performAttack(s,a.instanceId,t.instanceId,'INSECT',global.getCardDefinition(a.cardId).skills[1].id);runner.assertEqual(global.calculateMaxHp(a,s),1300);global.endTurn(s);runner.assertEqual(global.calculateMaxHp(a,s),1600);runner.assertEqual(a.currentHp,1600);runner.assertEqual(global.calculateMaxHp(t,s),1400);});
runner.test('Official poison scenario destroys after temporary HP expiry without territory acquisition',function(){var s=fixture(),a=h.putInsectOnField(s,'P1','set1_070'),t=h.putInsectOnField(s,'P2','set1_003',{hp:5000});global.performAttack(s,a.instanceId,t.instanceId,'INSECT',global.getCardDefinition(a.cardId).skills[1].id);global.endTurn(s);h.toMainPhase(s);global.applyDamage(s,t,a,1400,'ATTACK',t.instanceId,a.instanceId,{skill:{effects:[{type:'DAMAGE_DOES_NOT_HEAL'}]}});runner.assertEqual(a.zone,'FIELD');runner.assertEqual(a.currentHp,200);global.endTurn(s);runner.assertEqual(a.zone,'DISCARD');runner.assertEqual(s.pendingEffect,null);});
runner.test('Adding an active HP modifier preserves damage already received',function(){var s=fixture(),a=h.putInsectOnField(s,'P1','set1_003',{hp:1000});global.addStatModifier(s,a,{stat:'HP',amount:300});runner.assertEqual(global.calculateMaxHp(a,s),1700);runner.assertEqual(a.currentHp,1300);});
runner.test('SET2 black longhorn raises its own HP by 100 next opponent turn',function(){var raw=JSON.parse(JSON.stringify(global.getCardDefinition('set2_043')));raw.id='test_hp_043';raw.set=null;raw.implementationStatus='test';var d=new global.CardDefinition(raw);global.cardRegistry.register(d);var s=fixture(),a=h.putInsectOnField(s,'P1',d.id),t=h.putInsectOnField(s,'P2','set1_003');global.performAttack(s,a.instanceId,t.instanceId,'INSECT',d.skills[1].id);global.endTurn(s);runner.assertEqual(global.calculateMaxHp(a,s),500);runner.assertEqual(a.currentHp,500);runner.assertEqual(global.calculateMaxHp(t,s),1400);h.toMainPhase(s);global.endTurn(s);runner.assertEqual(global.calculateMaxHp(a,s),400);runner.assertEqual(a.currentHp,400);});
module.exports=runner;if(require.main===module)runner.runAll();
