'use strict';
var TestRunner=require('./lib.js');require('./engine-loader.js');require('../js/engine/cpu-agent.js');require('../js/ui/card-ui.js');require('../js/ui/battle-ui.js');var h=require('./helpers.js');var runner=new TestRunner();
function spellBattle(n){var s=h.newGame({rng:h.firstPlayerRng});if(s.phase===Phases.SET_PHASE)enterMainPhase(s);h.ensureCost(s,'P1',1);var spell=h.addToHandRaw(s,'P1',h.defById('jinkaichu_no_bakunetsudan')),targets=[];for(var i=0;i<n;i++)targets.push(h.putInsectOnField(s,'P2',i%2?'test_green_1':'test_blue_1',{hp:2000}));return{s:s,spell:spell,targets:targets};}
runner.test('FixBakunetsu1 複数対象で選択pending',function(){var b=spellBattle(2),r=useSpell(b.s,'P1',b.spell.instanceId);runner.assertTrue(r&&r.pending);runner.assertEqual(b.s.pendingEffect.type,'SPELL_TARGET_SELECTION');runner.assertEqual(b.s.pendingEffect.options.length,2);runner.assertEqual(b.spell.zone,ZONES.HAND);});
runner.test('FixBakunetsu2 選択対象だけ600ダメージ',function(){var b=spellBattle(2);useSpell(b.s,'P1',b.spell.instanceId);resolveSpellTargetSelection(b.s,'P1',b.targets[1].instanceId);runner.assertEqual(b.targets[0].currentHp,2000);runner.assertEqual(b.targets[1].currentHp,1400);runner.assertEqual(b.spell.zone,ZONES.DISCARD);});
runner.test('FixBakunetsu3 色倍率なし',function(){var b=spellBattle(1);useSpell(b.s,'P1',b.spell.instanceId);var e=getBattleEventsSince(b.s,0).filter(function(x){return x.type==='DAMAGE';})[0];runner.assertEqual(b.targets[0].currentHp,1400);runner.assertEqual(e.damage,600);runner.assertEqual(e.colorMultiplier,1);runner.assertEqual(e.damageType,'SPELL');});
runner.test('FixBakunetsu3b 対象1体なら即解決',function(){var b=spellBattle(1),r=useSpell(b.s,'P1',b.spell.instanceId);runner.assertTrue(!r.pending);runner.assertEqual(b.s.pendingEffect,null);runner.assertEqual(b.targets[0].currentHp,1400);});
runner.test('FixBakunetsu3c 術による破壊では縄張りを取らない',function(){var b=spellBattle(1),before=b.s.player('P2').territory.length;b.targets[0].currentHp=500;useSpell(b.s,'P1',b.spell.instanceId);runner.assertEqual(b.targets[0].zone,ZONES.DISCARD);runner.assertEqual(b.s.player('P2').territory.length,before);});
runner.test('FixBakunetsu4 Humanが盤面から任意の2体目を選択',function(){var b=spellBattle(2);useSpell(b.s,'P1',b.spell.instanceId);var ui=Object.create(BattleUI.prototype);ui.state=b.s;ui.cpuMode=false;ui.actionState={mode:'idle'};ui.render=function(){};ui.onFieldCardTap('P2',b.targets[1],null);runner.assertEqual(b.targets[0].currentHp,2000);runner.assertEqual(b.targets[1].currentHp,1400);runner.assertEqual(b.s.pendingEffect,null);});
runner.test('FixBakunetsu4b 対象選択開始時に詳細画面を閉じる',function(){var b=spellBattle(2),actions=null,hidden=false;var ui=Object.create(BattleUI.prototype);ui.state=b.s;ui.cpuMode=false;ui.actionState={mode:'idle'};ui.showCardDetail=function(card,a){actions=a;};ui.hideCardDetail=function(){hidden=true;};ui.render=function(){};ui.onHandCardTap('P1',b.spell);actions[0].onSelect();runner.assertTrue(hidden);runner.assertEqual(b.s.pendingEffect.type,'SPELL_TARGET_SELECTION');});
runner.test('FixBakunetsu5 CPUが合法対象を選択',function(){var b=spellBattle(2),s=b.s;s.activePlayerId='P2';s.player('P2').availableCost=1;s.player('P1').field=s.player('P2').field;s.player('P2').field=[];b.targets.forEach(function(t){t.ownerId=t.controllerId='P1';});s.player('P1').hand=s.player('P1').hand.filter(function(c){return c!==b.spell;});b.spell.ownerId=b.spell.controllerId='P2';s.player('P2').hand=[b.spell];var cpu=new CpuAgent('P2',{rng:function(){return .99;}}),a=cpu.decideMainPhaseAction(s);runner.assertEqual(a.type,'USE_SPELL');runner.assertTrue(s.player('P1').field.some(function(c){return c.instanceId===a.targetInstanceId;}));runner.assertTrue(cpu.executeAction(s,a));});
runner.test('FixBatta1 詳細は正式な具体文',function(){var s=h.newGame({rng:h.firstPlayerRng}),c=h.addToHandRaw(s,'P1',h.defById('batta_no_kyousou')),d=CardUI.getCardDetail(c,s);runner.assertEqual(d.cardEffects[0].text,'ターン終了時まで、自分のすべての虫の攻撃力を２００増やす。');});
function emptyDraw(a,b){var s=h.newGame({rng:h.firstPlayerRng});s.activePlayerId='P2';s.turnNumber=2;s.phase=Phases.DRAW_PHASE;s.manualDrawPlayers=['P2'];s.drewThisTurn=false;s.player('P2').deck=[];s.player('P1').territory=s.player('P1').territory.slice(0,a);s.player('P2').territory=s.player('P2').territory.slice(0,b);return s;}
runner.test('FixDeckOut1 最後の1枚では終了しない',function(){var s=emptyDraw(4,3),last=s.player('P2').hand.pop();last.zone=ZONES.DECK;s.player('P2').deck.push(last);drawCardOnce(s,'P2');runner.assertEqual(s.player('P2').deck.length,0);runner.assertEqual(s.phase,Phases.SET_PHASE);runner.assertEqual(s.winner,null);});
runner.test('FixDeckOut2 必要ドロー失敗で縄張り多数側が勝利',function(){var s=emptyDraw(5,2);drawCardOnce(s,'P2');runner.assertEqual(s.phase,Phases.GAME_OVER);runner.assertEqual(s.winner,'P1');});
runner.test('FixDeckOut3 先攻初手スキップは誤発火しない',function(){var s=h.newGame({rng:h.firstPlayerRng});s.player('P1').deck=[];runner.assertEqual(s.turnNumber,1);runner.assertEqual(s.phase,Phases.SET_PHASE);runner.assertEqual(s.winner,null);});
runner.test('FixDeckOut4 GAME_OVER後は双方追加行動不能',function(){var s=emptyDraw(5,2);drawCardOnce(s,'P2');var cpu=new CpuAgent('P2',{rng:function(){return 0;}});runner.assertEqual(cpu.step(s),null);var threw=false;try{enterSetPhase(s);}catch(e){threw=true;}runner.assertTrue(threw);});
runner.test('FixDeckOut5 同数なら勝者を推測しない',function(){var s=emptyDraw(3,3),blocked=false;try{drawCardOnce(s,'P2');}catch(e){blocked=/同数/.test(e.message);}runner.assertTrue(blocked);runner.assertEqual(s.winner,null);runner.assertEqual(s.phase,Phases.DRAW_PHASE);});
if(require.main===module)runner.runAll();module.exports=runner;
