'use strict';
require('./engine-loader.js'); require('../js/engine/cpu-agent.js');
var TestRunner=require('./lib.js'), h=require('./helpers.js'), runner=new TestRunner();
function main(){var s=h.newGame({rng:h.firstPlayerRng});h.toMainPhase(s);s.player('P1').field=[];s.player('P2').field=[];s.player('P1').territory=[];s.player('P2').territory=[];return s;}
function add(s,p,id,zone){var c=new global.CardInstance({instanceId:s.nextInstanceId(),cardId:id,ownerId:p,zone:zone});var d=global.getCardDefinition(id);c.baseHp=d.baseHp;c.currentHp=d.baseHp;s.player(p)[zone.toLowerCase()].push(c);return c;}
function attachment(s,p,id){return new global.CardInstance({instanceId:s.nextInstanceId(),cardId:id,ownerId:p,zone:global.ZONES.FIELD});}
runner.test('SET1P2 coverage 全106枚がPLAYABLE',function(){var all=global.cardRegistry.getBySet('BOOSTER_SET_1');runner.assertEqual(all.length,106);runner.assertEqual(all.filter(function(d){return !d.isPlayable();}).length,0);});
runner.test('SET1P2 multi-selection exact NとCPU共通resolver',function(){var s=main(),a=h.putInsectOnField(s,'P1','set1_028'),b=h.putInsectOnField(s,'P1','set1_031'),before=s.player('P1').hand.length,threw=false;global.createCardSelection(s,{playerId:'P1',options:[a.instanceId,b.instanceId],exactSelections:2,continuation:{type:'MOVE_SELECTED',from:'FIELD',to:'HAND'}});try{global.resolveCardSelection(s,'P1',[a.instanceId],true);}catch(e){threw=true;}runner.assert(threw);var cpu=new global.CpuAgent('P1',{rng:function(){return 0;}}),act=cpu.getPendingAction(s);runner.assert(cpu.executeAction(s,act));runner.assertEqual(s.player('P1').hand.length,before+2);});
runner.test('SET1P2 リオック代替召喚',function(){var s=main(),a=h.putInsectOnField(s,'P1','set1_028'),b=h.putInsectOnField(s,'P1','set1_031'),rio=h.addToHandRaw(s,'P1',global.getCardDefinition('set1_002'));global.summonInsect(s,'P1',rio.instanceId,{alternative:true});global.resolveCardSelection(s,'P1',[a.instanceId,b.instanceId],true);runner.assertEqual(rio.zone,'FIELD');runner.assertEqual(s.player('P1').discard.length,2);});
runner.test('SET1P2 毒のキバは回復しない',function(){var s=main(),a=h.putInsectOnField(s,'P1','set1_005'),d=h.putInsectOnField(s,'P2','set1_003',{hp:1400});global.performAttack(s,a.instanceId,d.instanceId,'INSECT',global.getCardDefinition('set1_005').skills[1].id);var hp=d.currentHp;global.endTurn(s);runner.assertEqual(d.currentHp,hp);});
runner.test('SET1P2 決死の一撃は双方を正しい順序で破壊',function(){var s=main(),a=h.putInsectOnField(s,'P1','set1_053'),d=h.putInsectOnField(s,'P2','set1_028',{hp:100});global.performAttack(s,a.instanceId,d.instanceId,'INSECT',global.getCardDefinition('set1_053').skills[1].id);runner.assertEqual(a.zone,'DISCARD');runner.assertEqual(d.zone,'DISCARD');});
runner.test('SET1P2 空蝉はDESTROY前に置換',function(){var s=main(),host=h.putInsectOnField(s,'P2','set1_028',{hp:100}),armor=attachment(s,'P2','set1_102'),events=[];host.attachments.push(armor);s.onBattleEvent=function(e){events.push(e.type);};global.destroyInsect(s,host.instanceId,'ATTACK','x',{});runner.assertEqual(host.zone,'FIELD');runner.assertEqual(host.currentHp,host.baseHp);runner.assert(events.indexOf('DESTROY')===-1);});
runner.test('SET1P2 蜜蝋の壁の縄張りlifecycle',function(){var s=main(),spell=h.addToHandRaw(s,'P1',global.getCardDefinition('set1_105'));global.useSpell(s,'P1',spell.instanceId);runner.assertEqual(spell.zone,'TERRITORY');runner.assertEqual(spell.faceDown,false);global.triggerTerritoryDrawSelection(s,'P1');global.resolveTerritoryDrawSelection(s,'P1',spell.instanceId);runner.assertEqual(spell.zone,'DISCARD');});
runner.test('SET1P2 叛逆の蛮勇atomic交換',function(){var s=main(),field=h.putInsectOnField(s,'P1','set1_028'),discard=add(s,'P1','set1_031',global.ZONES.DISCARD),spell=h.addToHandRaw(s,'P1',global.getCardDefinition('set1_120'));h.ensureCost(s,'P1',9);global.useSpell(s,'P1',spell.instanceId);global.resolveCardSelection(s,'P1',[discard.instanceId,field.instanceId],true);runner.assertEqual(discard.zone,'FIELD');runner.assertEqual(discard.attackedThisTurn,true);runner.assertEqual(field.zone,'DISCARD');});
runner.test('SET1P2 蠱毒の因果のtype routing',function(){var s=main(),spell=h.addToHandRaw(s,'P1',global.getCardDefinition('set1_119'));s.player('P1').deck=[];var top=add(s,'P1','set1_028',global.ZONES.DECK);h.ensureCost(s,'P1',9);global.useSpell(s,'P1',spell.instanceId);runner.assertEqual(top.zone,'FIELD');runner.assertEqual(top.runtimeFlags.destroyAtEndTurn,s.turnNumber);});
runner.test('SET1P2 埋葬虫は相手attachmentを破壊',function(){var s=main(),host=h.putInsectOnField(s,'P2','set1_028'),enh=attachment(s,'P2','set1_100'),spell=h.addToHandRaw(s,'P1',global.getCardDefinition('set1_128'));host.attachments.push(enh);h.ensureCost(s,'P1',9);global.useSpell(s,'P1',spell.instanceId);global.resolveCardSelection(s,'P1',[enh.instanceId],true);runner.assertEqual(host.attachments.length,0);runner.assertEqual(enh.zone,'DISCARD');});
runner.test('SET1P2 テナガ攻撃は選択順に2体へ攻撃',function(){var s=main(),a=h.putInsectOnField(s,'P1','set1_068'),x=h.putInsectOnField(s,'P2','set1_028',{hp:500}),y=h.putInsectOnField(s,'P2','set1_031',{hp:500}),skill=global.getCardDefinition('set1_068').skills[1],results=global.performMultiTargetAttack(s,a.instanceId,[x.instanceId,y.instanceId],skill.id);runner.assertEqual(results.length,2);runner.assertEqual(x.currentHp,200);runner.assertEqual(y.currentHp,200);});
runner.test('SET1P2 ミツツボアリの任意エサ追加はコストを増やさない',function(){var s=main(),ant=h.addToHandRaw(s,'P1',global.getCardDefinition('set1_027')),food=h.addToHandRaw(s,'P1',global.getCardDefinition('set1_028'));h.ensureCost(s,'P1',9);global.summonInsect(s,'P1',ant.instanceId);var cost=s.player('P1').availableCost;global.resolveCardSelection(s,'P1',[food.instanceId],true);runner.assertEqual(food.zone,'FOOD');runner.assertEqual(s.player('P1').availableCost,cost);});
runner.test('SET1P2 虹色光沢は使用時点の相手全体を指定色にする',function(){var s=main(),a=h.putInsectOnField(s,'P1','set1_039'),x=h.putInsectOnField(s,'P2','set1_028',{hp:999}),y=h.putInsectOnField(s,'P2','set1_031',{hp:999}),skill=global.getCardDefinition('set1_039').skills[1];global.performAttack(s,a.instanceId,x.instanceId,'INSECT',skill.id,null,{chosenColor:'BLUE'});runner.assertEqual(global.getEffectiveColor(x),'BLUE');runner.assertEqual(global.getEffectiveColor(y),'BLUE');});
runner.test('SET1P2 サバクトビバッタは直接攻撃時エサ返却後に縄張り選択',function(){var s=main(),a=h.putInsectOnField(s,'P1','set1_073'),food=h.addToFoodRaw(s,'P2',global.getCardDefinition('set1_028')),terr=h.addToTerritoryRaw(s,'P2',global.getCardDefinition('set1_031'));global.performAttack(s,a.instanceId,null,'LEADER');runner.assertEqual(s.pendingEffect.selectionPurpose,'DIRECT_ATTACK_FOOD_RETURN');global.resolveCardSelection(s,'P2',[food.instanceId],true);runner.assertEqual(food.zone,'HAND');runner.assertEqual(s.pendingEffect.type,'TERRITORY_DRAW_SELECTION');});
runner.test('SET1P2 コバネイナゴはエサ1枚を追加コストにする',function(){var s=main(),a=h.putInsectOnField(s,'P1','set1_084'),food=h.addToFoodRaw(s,'P1',global.getCardDefinition('set1_028')),d=h.putInsectOnField(s,'P2','set1_031',{hp:999}),skill=global.getCardDefinition('set1_084').skills[1];global.performAttack(s,a.instanceId,d.instanceId,'INSECT',skill.id,food.instanceId);runner.assertEqual(food.zone,'DISCARD');});
runner.test('SET1P2 attachment transferは所有者を保持する',function(){var s=main(),a=h.putInsectOnField(s,'P1','set1_093'),dest=h.putInsectOnField(s,'P1','set1_028'),enh=attachment(s,'P1','set1_100'),d=h.putInsectOnField(s,'P2','set1_031',{hp:999}),skill=global.getCardDefinition('set1_093').skills[1];a.attachments.push(enh);global.performAttack(s,a.instanceId,d.instanceId,'INSECT',skill.id,null,{attachmentInstanceId:enh.instanceId,destinationInstanceId:dest.instanceId});runner.assertEqual(dest.attachments[0],enh);runner.assertEqual(enh.ownerId,'P1');});
runner.test('SET1P2 不滅の王台はhost残存中だけ縄張り取得を抑止',function(){var s=main(),a=h.putInsectOnField(s,'P1','set1_003'),host=h.putInsectOnField(s,'P2','set1_031'),victim=h.putInsectOnField(s,'P2','set1_028',{hp:100}),throne=attachment(s,'P2','set1_110');host.attachments.push(throne);h.addToTerritoryRaw(s,'P2',global.getCardDefinition('set1_028'));global.performAttack(s,a.instanceId,victim.instanceId,'INSECT');runner.assertEqual(s.pendingEffect,null);});
runner.test('SET1P2 鋏虫は攻撃由来縄張りのとびだすを抑止',function(){var s=main(),a=h.putInsectOnField(s,'P1','set1_003'),scissors=attachment(s,'P1','set1_111'),d=h.putInsectOnField(s,'P2','set1_028',{hp:100}),jump=h.addToTerritoryRaw(s,'P2',global.getCardDefinition('set1_009'));a.attachments.push(scissors);global.performAttack(s,a.instanceId,d.instanceId,'INSECT');global.resolveTerritoryDrawSelection(s,'P2',jump.instanceId);runner.assertEqual(jump.zone,'HAND');runner.assertEqual(s.pendingEffect,null);});
runner.test('SET1P2 瀬戸際は同色最大2体を順番に場へ出す',function(){var s=main(),x=h.addToFoodRaw(s,'P1',global.getCardDefinition('set1_028')),y=h.addToFoodRaw(s,'P1',global.getCardDefinition('set1_031')),spell=h.addToHandRaw(s,'P1',global.getCardDefinition('set1_116'));h.ensureCost(s,'P1',9);if(global.getCardDefinition(x.cardId).color!==global.getCardDefinition(y.cardId).color){y.cardId=x.cardId;}global.useSpell(s,'P1',spell.instanceId);global.resolveCardSelection(s,'P1',[x.instanceId,y.instanceId],true);runner.assertEqual(x.zone,'FIELD');runner.assertEqual(y.zone,'FIELD');});
runner.test('SET1P2 繚乱は同コスト手札/場交換',function(){var s=main(),field=h.putInsectOnField(s,'P1','set1_028'),hand=h.addToHandRaw(s,'P1',global.getCardDefinition('set1_028')),spell=h.addToHandRaw(s,'P1',global.getCardDefinition('set1_126'));h.ensureCost(s,'P1',9);global.useSpell(s,'P1',spell.instanceId);global.resolveCardSelection(s,'P1',[hand.instanceId,field.instanceId],true);runner.assertEqual(hand.zone,'FIELD');runner.assertEqual(field.zone,'HAND');});
module.exports=runner;
