'use strict';
require('./engine-loader.js');require('../js/engine/cpu-agent.js');
var h=require('./helpers.js'),Runner=require('./lib.js'),runner=new Runner();
var raw=JSON.parse(JSON.stringify(global.getCardDefinition('set2_040')));raw.id='test_food_concealment';raw.set=null;raw.implementationStatus='test';var def=new global.CardDefinition(raw);global.cardRegistry.register(def);
function fixture(){var s=h.newGame({rng:h.firstPlayerRng});h.toMainPhase(s);s.turnNumber=3;s.player('P2').territory=[];s.player('P2').field=[];s.player('P2').food=[];return {s:s,a:h.putInsectOnField(s,'P1',def.id),food:h.addToFoodRaw(s,'P2',global.getCardDefinition('set1_003')),t:h.addToTerritoryRaw(s,'P2',global.getCardDefinition('set1_009'))};}
runner.test('Silver tackle offers optional food concealment after territory and jump-out',function(){var f=fixture();global.performAttack(f.s,f.a.instanceId,null,'LEADER',def.skills[0].id);global.resolveTerritoryDrawSelection(f.s,'P2',f.t.instanceId);runner.assertEqual(f.s.pendingEffect.type,'TERRITORY_DRAW_CHOICE');global.resolvePendingTerritoryChoice(f.s,'USE_TOBIDASU');runner.assertEqual(f.s.pendingEffect.selectionPurpose,'FLIP_OPPONENT_FOOD');runner.assertEqual(f.s.pendingEffect.playerId,'P1');global.resolveCardSelection(f.s,'P1',[f.food.instanceId],true);runner.assert(f.food.faceDown);runner.assertEqual(f.s.pendingEffect,null);global.endTurn(f.s);h.toMainPhase(f.s);runner.assertEqual(f.s.player('P2').availableCost,1);});
runner.test('Food concealment can be declined and never triggers without acquired territory',function(){var f=fixture();global.performAttack(f.s,f.a.instanceId,null,'LEADER',def.skills[0].id);global.resolveTerritoryDrawSelection(f.s,'P2',f.t.instanceId);global.resolvePendingTerritoryChoice(f.s,'TAKE_TO_HAND');global.resolveCardSelection(f.s,'P1',[],true);runner.assert(!f.food.faceDown);runner.assertEqual(f.s.pendingEffect,null);var g=fixture();g.s.player('P2').territory=[];h.putInsectOnField(g.s,'P2','set1_003',{hp:5000});global.performAttack(g.s,g.a.instanceId,g.s.player('P2').field[0].instanceId,'INSECT',def.skills[0].id);runner.assertEqual(g.s.pendingEffect,null);});
runner.test('CPU resolves optional food concealment without pending deadlock',function(){var f=fixture();global.performAttack(f.s,f.a.instanceId,null,'LEADER',def.skills[0].id);global.resolveTerritoryDrawSelection(f.s,'P2',f.t.instanceId);global.resolvePendingTerritoryChoice(f.s,'TAKE_TO_HAND');var cpu=new global.CpuAgent('P1');runner.assert(cpu.executeAction(f.s,cpu.getPendingAction(f.s)));runner.assertEqual(f.s.pendingEffect,null);});
runner.test('Face-down food supplies cost but has no color or legal spell target identity',function(){var f=fixture();f.food.faceDown=true;f.s.activePlayerId='P2';var ant=h.putInsectOnField(f.s,'P2','set1_021');var antSkill=global.getCardDefinition(ant.cardId).skills[0];runner.assertEqual(global.getEffectiveAP(f.s,ant,antSkill.baseAp,antSkill),0);var spell=h.addToHandRaw(f.s,'P2',global.getCardDefinition('set1_121'));runner.assertEqual(global.getSpellTargetCandidates(f.s,'P2',spell.instanceId).length,0);});
module.exports=runner;if(require.main===module)runner.runAll();
