'use strict';
require('./engine-loader.js');require('../js/engine/cpu-agent.js');
var h=require('./helpers.js'),Runner=require('./lib.js'),runner=new Runner();
var raw=JSON.parse(JSON.stringify(global.getCardDefinition('set2_011')));raw.id='test_blind_011';raw.set=null;raw.implementationStatus='test';var def=new global.CardDefinition(raw);global.cardRegistry.register(def);
function fixture(){var s=h.newGame({rng:h.firstPlayerRng});h.toMainPhase(s);s.turnNumber=3;s.player('P2').territory=[];s.player('P2').field=[];return {s:s,a:h.putInsectOnField(s,'P1',def.id),x:h.putInsectOnField(s,'P2','set1_003'),y:h.putInsectOnField(s,'P2','set1_003')};}
runner.test('Blind attack delegates legal target to defender and does no damage before choice',function(){var f=fixture();global.performAttack(f.s,f.a.instanceId,f.x.instanceId,'INSECT',def.skills[0].id);runner.assertEqual(f.s.pendingEffect.playerId,'P2');runner.assertEqual(f.s.pendingEffect.selectionPurpose,'OPPONENT_ATTACK_TARGET');runner.assertEqual(f.x.currentHp,1400);var rejected=false;try{global.resolveCardSelection(f.s,'P1',[f.y.instanceId],true);}catch(e){rejected=true;}runner.assert(rejected);global.resolveCardSelection(f.s,'P2',[f.y.instanceId],true);runner.assertEqual(f.x.currentHp,1400);runner.assertEqual(f.y.currentHp,900);runner.assertEqual(f.s.pendingEffect,null);});
runner.test('Blind attack honors lure and ignores hidden targets',function(){var f=fixture();f.x.cardId='set1_080';f.y.faceDown=true;global.performAttack(f.s,f.a.instanceId,f.x.instanceId,'INSECT',def.skills[0].id);runner.assertEqual(f.s.pendingEffect,null);runner.assert(f.a.attackedThisTurn);});
runner.test('CPU defender resolves blind attack without stealing attacking turn',function(){var f=fixture();global.performAttack(f.s,f.a.instanceId,f.x.instanceId,'INSECT',def.skills[0].id);var cpu=new global.CpuAgent('P2');runner.assert(cpu.executeAction(f.s,cpu.getPendingAction(f.s)));runner.assertEqual(f.s.pendingEffect,null);runner.assertEqual(f.s.activePlayerId,'P1');global.endTurn(f.s);runner.assertEqual(f.s.activePlayerId,'P2');});
module.exports=runner;if(require.main===module)runner.runAll();
