'use strict';require('./engine-loader.js');var TestRunner=require('./lib.js'),h=require('./helpers.js'),runner=new TestRunner();
function game(){var s=h.newGame({rng:h.firstPlayerRng});h.toMainPhase(s);return s;}
function playable(id,suffix){var old=global.getCardDefinition('test_'+id+suffix);if(old)return old;var raw=JSON.parse(JSON.stringify(global.getCardDefinition(id)));raw.id='test_'+id+suffix;raw.implementationStatus='test';var d=new global.CardDefinition(raw);d.cardEffects=raw.cardEffects;d.enhancementEffects=raw.enhancementEffects;global.cardRegistry.register(d);return d;}
function hand(s,p,d){return h.addToHandRaw(s,p,d);}
function discard(s,p,id){var c=hand(s,p,global.getCardDefinition(id));global.moveCard(s,c.instanceId,'HAND','DISCARD',{playerId:p});return c;}
runner.test('SET3 tracked revival summons serially, attaches to chosen host and suppresses entry keyword',function(){var s=game(),def=playable('set3_048','a'),enh=hand(s,'P1',def),first=discard(s,'P1','set3_039'),second=discard(s,'P1','set1_003');s.player('P1').availableCost=10;global.useEnhancement(s,'P1',enh.instanceId);global.resolveCardSelection(s,'P1',[first.instanceId,second.instanceId],true);runner.assertEqual(s.pendingEffect.selectionPurpose,'TRACKED_REVIVAL_HOST');global.resolveCardSelection(s,'P1',[first.instanceId],true);runner.assertEqual(s.pendingEffect,null);runner.assertEqual(first.zone,'FIELD');runner.assertEqual(second.zone,'FIELD');runner.assert(first.runtimeFlags.suppressKeywordSkills);runner.assertEqual(first.attachments[0].instanceId,enh.instanceId);});
runner.test('SET3 tracked revival destroys only original instances still on field when attachment leaves',function(){var s=game(),def=playable('set3_048','b'),enh=hand(s,'P1',def),first=discard(s,'P1','set1_003'),second=discard(s,'P1','set1_004');s.player('P1').availableCost=10;global.useEnhancement(s,'P1',enh.instanceId);global.resolveCardSelection(s,'P1',[first.instanceId,second.instanceId],true);global.resolveCardSelection(s,'P1',[first.instanceId],true);global.moveCard(s,second.instanceId,'FIELD','HAND',{playerId:'P1'});global.moveCard(s,first.instanceId,'FIELD','HAND',{playerId:'P1'});runner.assertEqual(first.zone,'HAND');runner.assertEqual(second.zone,'HAND');});
runner.test('SET3 tracked revival suppresses granted and printed keyword targeting protection',function(){var s=game(),def=playable('set3_048','c'),enh=hand(s,'P1',def),mimic=discard(s,'P1','set3_034'),other=discard(s,'P1','set1_004');s.player('P1').availableCost=10;global.useEnhancement(s,'P1',enh.instanceId);global.resolveCardSelection(s,'P1',[mimic.instanceId,other.instanceId],true);global.resolveCardSelection(s,'P1',[other.instanceId],true);global.endTurn(s);h.toMainPhase(s);var attacker=h.putInsectOnField(s,'P2','set1_003');runner.assert(global.getLegalAttackTargets(s,attacker.instanceId).some(function(t){return t.instance&&t.instance.instanceId===mimic.instanceId;}));});
runner.test('SET3 secret book prevents targeting next opponent turn and returns only after attack destruction',function(){var s=game(),def=playable('set3_049','a'),host=h.putInsectOnField(s,'P1','set1_003',{hp:100}),enh=hand(s,'P1',def);s.player('P1').availableCost=10;global.useEnhancement(s,'P1',enh.instanceId,host.instanceId);global.endTurn(s);h.toMainPhase(s);var attacker=h.putInsectOnField(s,'P2','kabutomushi');runner.assert(global.getLegalAttackTargets(s,attacker.instanceId).every(function(t){return !t.instance||t.instance.instanceId!==host.instanceId;}));global.destroyInsect(s,host.instanceId,'ATTACK',attacker.instanceId,{skill:global.getCardDefinition(attacker.cardId).skills[0]});runner.assertEqual(enh.zone,'HAND');});
runner.test('SET3 blood pact pays two selected territories instead of generated cost and destroys target',function(){var s=game(),def=playable('set3_051','a'),spell=hand(s,'P1',def),target=h.putInsectOnField(s,'P2','set1_003'),t1=h.addToTerritoryRaw(s,'P1',global.getCardDefinition('set1_004')),t2=h.addToTerritoryRaw(s,'P1',global.getCardDefinition('set1_005'));s.player('P1').availableCost=0;global.useSpell(s,'P1',spell.instanceId,target.instanceId);global.resolveChoiceSelection(s,'P1','TERRITORY');runner.assertEqual(s.pendingEffect.selectionPurpose,'SPELL_TERRITORY_PAYMENT');s.pendingEffect=JSON.parse(JSON.stringify(s.pendingEffect));global.resolveCardSelection(s,'P1',[t1.instanceId,t2.instanceId],true);runner.assertEqual(target.zone,'DISCARD');runner.assertEqual(spell.zone,'DISCARD');runner.assertEqual(s.player('P1').availableCost,0);});
runner.test('SET3 ambush grants suffix tobidasu once and does not reactivate after territory reaches zero',function(){var s=game(),def=playable('set3_060','a'),spell=hand(s,'P1',def);s.player('P1').availableCost=10;global.useSpell(s,'P1',spell.instanceId);runner.assert(s.player('P1').territoryTriggerGrant.active);var grass=global.getCardDefinition('set3_032'),card=h.addToTerritoryRaw(s,'P1',grass);s.player('P1').territory=s.player('P1').territory.filter(function(c){return c===card;});global.triggerTerritoryDrawSelection(s,'P1',{});global.resolveTerritoryDrawSelection(s,'P1',card.instanceId);runner.assertEqual(s.pendingEffect,null);runner.assertEqual(card.zone,'HAND');runner.assert(!s.player('P1').territoryTriggerGrant.active);h.addToTerritoryRaw(s,'P1',grass);runner.assert(!s.player('P1').territoryTriggerGrant.active);});
runner.test('SET3 white shell ignores weakness only on next opponent turn',function(){var s=game(),def=playable('set3_021','a'),host=h.putInsectOnField(s,'P1',def.id);global.resolveFieldEntryEffects(s,host.instanceId);global.endTurn(s);h.toMainPhase(s);var attacker=h.putInsectOnField(s,'P2','set1_003');var result=global.performAttack(s,attacker.instanceId,host.instanceId,'INSECT',global.getCardDefinition(attacker.cardId).skills[0].id);runner.assertEqual(result.multiplier,1);});
runner.test('SET3 strange arms blocks insects summoned by spell during that turn',function(){var s=game();h.putInsectOnField(s,'P2','set3_022');var summon=playable('set3_050','a'),spell=hand(s,'P1',summon),bee=hand(s,'P1',global.getCardDefinition('set2_005'));s.player('P1').availableCost=10;global.useSpell(s,'P1',spell.instanceId);global.resolveCardSelection(s,'P1',[bee.instanceId],true);runner.assertEqual(global.getLegalAttackTargets(s,bee.instanceId).length,0);});
runner.test('SET3 rainbow reflection changes only face-up food through end turn',function(){var s=game(),def=playable('set3_024','a'),source=h.putInsectOnField(s,'P1',def.id),visible=h.addToFoodRaw(s,'P1',global.getCardDefinition('set1_003')),hidden=h.addToFoodRaw(s,'P1',global.getCardDefinition('set1_004'));hidden.faceDown=true;global.resolveFieldEntryEffects(s,source.instanceId);global.resolveChoiceSelection(s,'P1','GREEN');runner.assertEqual(global.getEffectiveColor(visible),'GREEN');runner.assert(global.getEffectiveColor(hidden)!=='GREEN');global.endTurn(s);runner.assert(global.getEffectiveColor(visible)!=='GREEN');});
runner.test('SET3 thorn mimic gains AP for territory draws on opponent turn and clears at turn end',function(){var s=game(),def=global.getCardDefinition('set3_033'),host=h.putInsectOnField(s,'P1',def.id),territory=h.addToTerritoryRaw(s,'P1',global.getCardDefinition('set1_003'));global.resolveFieldEntryEffects(s,host.instanceId);global.endTurn(s);h.toMainPhase(s);global.triggerTerritoryDrawSelection(s,'P1',{});global.resolveTerritoryDrawSelection(s,'P1',territory.instanceId);runner.assertEqual(global.getEffectiveAP(s,host,700,def.skills[0]),1000);global.endTurn(s);runner.assertEqual(global.getEffectiveAP(s,host,700,def.skills[0]),700);});
runner.test('SET3 territory armor optionally attaches before suspended attack continuation resumes',function(){var s=game(),host=h.putInsectOnField(s,'P1','set1_003'),armor=h.addToTerritoryRaw(s,'P1',global.getCardDefinition('set3_046'));global.triggerTerritoryDrawSelection(s,'P1',{});global.resolveTerritoryDrawSelection(s,'P1',armor.instanceId);runner.assertEqual(s.pendingEffect.selectionPurpose,'ATTACH_FROM_TERRITORY');global.resolveCardSelection(s,'P1',[host.instanceId],true);runner.assertEqual(host.attachments[0].instanceId,armor.instanceId);runner.assertEqual(global.calculateMaxHp(host,s),global.getCardDefinition(host.cardId).baseHp+700);});
module.exports=runner;if(require.main===module){runner.runAll();}
