'use strict';require('./engine-loader.js');require('../js/engine/cpu-agent.js');var h=require('./helpers.js'),Runner=require('./lib.js'),runner=new Runner();
function clone(source){var raw=JSON.parse(JSON.stringify(source));raw.id='test_runtime_'+source.id;raw.set=null;raw.implementationStatus='test';var d=new global.CardDefinition(raw);Object.keys(raw).forEach(function(k){d[k]=raw[k];});global.cardRegistry.register(d);return d;}
function drain(s){var agents={P1:new global.CpuAgent('P1',{rng:function(){return 0;}}),P2:new global.CpuAgent('P2',{rng:function(){return 0;}})};for(var i=0;s.pendingEffect&&i<40;i++){var p=s.pendingEffect,a=agents[p.playerId],action=a&&a.getPendingAction(s);if(!action||!a.executeAction(s,action))throw new Error('unresolved '+p.type+' '+p.selectionPurpose);}if(s.pendingEffect)throw new Error('pending loop');}
global.cardRegistry.getBySet('BOOSTER_SET_3').forEach(function(source){var def=clone(source);runner.test(source.id+' loads and completes a production Battle action',function(){var s=h.newGame({rng:h.firstPlayerRng});h.toMainPhase(s);s.turnNumber=3;s.player('P1').hand=[];s.player('P1').field=[];s.player('P1').discard=[];s.player('P1').food=[];s.player('P2').field=[];s.player('P2').territory=[];var held=h.addToHandRaw(s,'P1',def);h.ensureCost(s,'P1',30);
if(def.type===global.CardTypes.INSECT){global.summonInsect(s,'P1',held.instanceId);drain(s);runner.assertEqual(held.zone,'FIELD');}
else if(def.type===global.CardTypes.ENHANCEMENT){if(source.id==='set3_048'){var a=h.addToHandRaw(s,'P1',global.getCardDefinition('set1_003')),b=h.addToHandRaw(s,'P1',global.getCardDefinition('set1_004'));global.moveCard(s,a.instanceId,'HAND','DISCARD',{playerId:'P1'});global.moveCard(s,b.instanceId,'HAND','DISCARD',{playerId:'P1'});global.useEnhancement(s,'P1',held.instanceId);drain(s);runner.assertEqual(held.zone,'FIELD');}else{var host=h.putInsectOnField(s,'P1','set1_003');global.useEnhancement(s,'P1',held.instanceId,host.instanceId);drain(s);runner.assertEqual(host.attachments[0],held);}}
else{var target=h.putInsectOnField(s,'P2','set1_003',{hp:100000}),own=h.putInsectOnField(s,'P1','set1_004');if(source.id==='set3_050'){h.addToHandRaw(s,'P1',global.getCardDefinition('set2_005'));}if(source.id==='set3_051'){h.addToTerritoryRaw(s,'P1',global.getCardDefinition('set1_003'));h.addToTerritoryRaw(s,'P1',global.getCardDefinition('set1_004'));}if(source.id==='set3_052'){h.addToTerritoryRaw(s,'P1',global.getCardDefinition('set1_003'));}if(source.id==='set3_056'){for(var i=0;i<5;i++){h.addToHandRaw(s,'P1',global.getCardDefinition('set1_003'));h.addToHandRaw(s,'P2',global.getCardDefinition('set1_003'));}}if(source.id==='set3_057'){var food=h.addToFoodRaw(s,'P1',global.getCardDefinition('set1_003'));food.faceDown=true;}var candidates=global.getSpellTargetCandidates(s,'P1',held.instanceId),chosen=candidates.length?candidates[0].instanceId:null;global.useSpell(s,'P1',held.instanceId,chosen);drain(s);runner.assertEqual(held.zone,'DISCARD');}
drain(s);runner.assertEqual(s.pendingEffect,null);global.endTurn(s);runner.assertEqual(s.activePlayerId,'P2');});});
module.exports=runner;if(require.main===module)runner.runAll();
