'use strict';require('./engine-loader.js');var TestRunner=require('./lib.js');var h=require('./helpers.js');var runner=new TestRunner();
function game(){var s=h.newGame({rng:h.firstPlayerRng});h.toMainPhase(s);return s;}
function food(s,p,id){return h.addToFoodRaw(s,p,global.getCardDefinition(id));}
function exchangeSkill(){return global.getCardDefinition('set3_031').skills[1];}
runner.test('SET3 reverse exchange is unusable without a face-up opponent food insect',function(){var s=game(),a=h.putInsectOnField(s,'P1','set3_031');h.putInsectOnField(s,'P2','set1_003');runner.assertEqual(global.getLegalAttackTargets(s,a.instanceId,exchangeSkill().id).length,0);var hidden=food(s,'P2','set1_004');hidden.faceDown=true;runner.assertEqual(global.getLegalAttackTargets(s,a.instanceId,exchangeSkill().id).length,0);h.addToFoodRaw(s,'P2',global.getCardDefinition('niji_no_kakehashi'));runner.assertEqual(global.getLegalAttackTargets(s,a.instanceId,exchangeSkill().id).length,0);});
runner.test('SET3 reverse exchange moves atomically and damages the incoming insect',function(){var s=game(),a=h.putInsectOnField(s,'P1','set3_031'),old=h.putInsectOnField(s,'P2','set1_003'),incoming=food(s,'P2','set1_004');var result=global.performAttack(s,a.instanceId,old.instanceId,'INSECT',exchangeSkill().id);runner.assert(result.pending);runner.assertEqual(s.pendingEffect.selectionPurpose,'ATTACK_DEFENDER_EXCHANGE');global.resolveCardSelection(s,'P1',[incoming.instanceId],true);runner.assertEqual(old.zone,'FOOD');runner.assertEqual(incoming.zone,'FIELD');runner.assertEqual(incoming.currentHp,global.getCardDefinition(incoming.cardId).baseHp);runner.assert(a.attackedThisTurn);});
runner.test('SET3 reverse exchange fully resolves incoming entry choice before attack damage',function(){var s=game(),a=h.putInsectOnField(s,'P1','set3_031'),old=h.putInsectOnField(s,'P2','set1_003'),incoming=food(s,'P2','set3_039'),other=h.putInsectOnField(s,'P1','set1_004');global.performAttack(s,a.instanceId,old.instanceId,'INSECT',exchangeSkill().id);global.resolveCardSelection(s,'P1',[incoming.instanceId],true);runner.assertEqual(s.pendingEffect.selectionPurpose,'ON_ENTER_FIELD_DAMAGE');runner.assert(!a.attackedThisTurn);global.resolveCardSelection(s,'P2',[other.instanceId],true);runner.assert(a.attackedThisTurn);runner.assertEqual(incoming.zone,'FIELD');});
runner.test('SET3 reverse exchange routes a captured defender to its owner food',function(){var s=game(),a=h.putInsectOnField(s,'P1','set3_031'),old=h.putInsectOnField(s,'P2','set1_003'),incoming=food(s,'P2','set1_004');old.ownerId='P1';global.performAttack(s,a.instanceId,old.instanceId,'INSECT',exchangeSkill().id);global.resolveCardSelection(s,'P1',[incoming.instanceId],true);runner.assert(s.player('P1').food.indexOf(old)!==-1);runner.assert(s.player('P2').food.indexOf(old)===-1);});
runner.test('SET3 reverse exchange JSON-restores its selection continuation',function(){var s=game(),a=h.putInsectOnField(s,'P1','set3_031'),old=h.putInsectOnField(s,'P2','set1_003'),incoming=food(s,'P2','set1_004');global.performAttack(s,a.instanceId,old.instanceId,'INSECT',exchangeSkill().id);s.pendingEffect=JSON.parse(JSON.stringify(s.pendingEffect));global.resolveCardSelection(s,'P1',[incoming.instanceId],true);runner.assert(a.attackedThisTurn);runner.assertEqual(incoming.zone,'FIELD');});
module.exports=runner;if(require.main===module){runner.runAll();}
