'use strict';
var TestRunner=require('./lib.js');require('./engine-loader.js');
var data=require('../js/cards/full-catalog-data.js');
var loader=require('../js/cards/catalog-card-loader.js');
var catalog=require('../shared/card-data/registry-catalog.js');
require('../shared/ui-presenter.js');
var core=require('../toolbox/toolbox-core.js');
var runner=new TestRunner();
function cards(){var r=new global.CardRegistry();global.cardRegistry.getAll().forEach(function(c){r.register(c);});loader.registerCatalogDefinitions(r,data);return catalog.fromRegistry(r);}
runner.test('SET8 catalog contains 64 consecutively numbered non-playable records',function(){var c=data.filter(function(x){return x.set==='BOOSTER_SET_8';});runner.assertEqual(c.length,64);runner.assertEqual(c.map(function(x){return x.officialNumber;}).join(','),Array.from({length:64},function(_,i){return (i+1)+'/64';}).join(','));runner.assert(c.every(function(x){return x.implementationStatus==='RESEARCHED';}));runner.assertEqual(c.filter(function(x){return x.type==='INSECT';}).length,46);runner.assertEqual(c.filter(function(x){return x.type==='ENHANCEMENT';}).length,8);runner.assertEqual(c.filter(function(x){return x.type==='SPELL';}).length,10);});
runner.test('565-card catalog keeps 309 playable cards and all SET8 cards in unavailable filter',function(){var c=cards();runner.assertEqual(c.length,565);runner.assertEqual(c.filter(function(x){return x.playable;}).length,309);runner.assertEqual(core.buildCatalogView(c,{set:'BOOSTER_SET_8',implementationStatusGroup:'UNAVAILABLE'},'officialNumber',global.MushijingiUiPresenter.statusGroup).length,64);runner.assertEqual(core.buildCatalogView(c,{set:'BOOSTER_SET_8',implementationStatusGroup:'PLAYABLE'},'officialNumber',global.MushijingiUiPresenter.statusGroup).length,0);});
runner.test('SET8 details contain complete attacks, traits, effects and provenance',function(){var c=data.filter(function(x){return x.set==='BOOSTER_SET_8';});runner.assertEqual(c.length,64);c.forEach(function(x){runner.assert(x.name&&x.rarity&&x.officialNumber&&x.sourceRefs.length>=2,x.id);if(x.type==='INSECT'){runner.assert(x.skills.length&&x.baseHp>0&&x.color,x.id);x.skills.forEach(function(s){runner.assert(s.name&&s.baseAp!=null,x.id);});runner.assert(x.description,x.id);}else{runner.assert((x.cardEffects.concat(x.enhancementEffects)).every(function(e){return e.effectText;}),x.id);runner.assert(x.cardEffects.length+x.enhancementEffects.length>0,x.id);}});});
runner.test('SET8 rarity counts derive from individual cards',function(){var counts=data.filter(function(x){return x.set==='BOOSTER_SET_8';}).reduce(function(a,x){a[x.rarity]=(a[x.rarity]||0)+1;return a;},{});runner.assertEqual(JSON.stringify(Object.keys(counts).sort().map(function(k){return [k,counts[k]];})),JSON.stringify([['LR',5],['N',21],['R',17],['SR',14],['UR',7]]));});
runner.test('Every SET8 printing saves in a legal twenty-card deck but is refused for Battle',function(){var all=cards(),set=all.filter(function(c){return c.set==='BOOSTER_SET_8';});set.forEach(function(c){var deck=core.createDeck({deckId:'deck:set8-audit',deckName:'SET8',cardDataVersion:'card-registry/1',rulesetId:'ruleset:standard:v1'});all.filter(function(x){return x.playable&&x.name!==c.name;}).slice(0,9).forEach(function(x){deck=core.addCatalogCard(deck,x);deck=core.addCatalogCard(deck,x);});deck=core.addCatalogCard(deck,c);deck=core.addCatalogCard(deck,c);var v=core.validateDeck(deck,all);runner.assert(v.storable,c.name+' saves');runner.assert(!v.battleReady,c.name+' cannot battle');});});
runner.test('SET8 same-name versions still share the two-card limit with earlier printings',function(){var all=cards(),set=all.filter(function(c){return c.set==='BOOSTER_SET_8';});var matches=0;set.forEach(function(c){var earlier=all.find(function(x){return x.set!=='BOOSTER_SET_8'&&x.name===c.name;});if(!earlier)return;matches++;var deck=core.createDeck({deckId:'deck:reprint-set8',cardDataVersion:'card-registry/1',rulesetId:'ruleset:standard:v1'});deck=core.addCatalogCard(deck,earlier);deck=core.addCatalogCard(deck,earlier);deck=core.addCatalogCard(deck,c);runner.assert(core.validateDeck(deck,all).errors.some(function(e){return e.includes('同名合計2枚まで');}),c.name);});runner.assert(matches>=4,'known reprints covered');});
runner.test('SET8 description and categorized rulings survive the production presenter',function(){var all=cards(),p=global.MushijingiUiPresenter;all.filter(function(c){return c.set==='BOOSTER_SET_8';}).forEach(function(c){var d=p.presentCardDetail(c,global.CardEffectFormatter);if(c.type==='INSECT')runner.assert(d.description.length>0,c.name);runner.assertEqual(d.rulings.length,c.rulings.length,c.name);});});
module.exports=runner;
